services:
  db:
    image: postgres:15-alpine
    container_name: grunland_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - grunland_network
 
  redis:
    image: redis:7-alpine
    container_name: grunland_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - grunland_network

  fastapi-app:
    build: .
    container_name: grunland_fastapi
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=docker
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app/app
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - grunland_network

  pdf-worker:
    build: .
    command: python -m app.services.pdf_worker
    environment:
      - ENVIRONMENT=docker
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app/app 
    depends_on:
      - db 
      - redis 
    restart: unless-stopped 
    networks:
      - grunland_network 
    deploy:
      replicas: 2
    
  email-worker:
    build: .
    command: python -m app.services.email_worker
    environment:
      - ENVIRONMENT=docker
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app/app
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - grunland_network
    deploy:
      replicas: 2

  rq-dashboard:
    image: eoranged/rq-dashboard
    container_name: grunland_rq_dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    depends_on:
      - redis 
    networks:
      - grunland_network

volumes:
  postgres_data:

networks:
  grunland_network:
    driver: bridge