name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '*'
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3 

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.13.3'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests 
        run: |
          pytest app/tests/test_user_router.py 
          pytest app/tests/test_admin_router.py
          pytest app/tests/test_auth_router.py
          